//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCpart.ActionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Action", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Action : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Action_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Action_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Action_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Action_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ActionService.Car_Order[] Car_OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Action_ID {
            get {
                return this.Action_IDField;
            }
            set {
                if ((this.Action_IDField.Equals(value) != true)) {
                    this.Action_IDField = value;
                    this.RaisePropertyChanged("Action_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action_Name {
            get {
                return this.Action_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Action_NameField, value) != true)) {
                    this.Action_NameField = value;
                    this.RaisePropertyChanged("Action_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Action_Price {
            get {
                return this.Action_PriceField;
            }
            set {
                if ((this.Action_PriceField.Equals(value) != true)) {
                    this.Action_PriceField = value;
                    this.RaisePropertyChanged("Action_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Action_Info {
            get {
                return this.Action_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Action_InfoField, value) != true)) {
                    this.Action_InfoField = value;
                    this.RaisePropertyChanged("Action_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MVCpart.ActionService.Car_Order[] Car_Order {
            get {
                return this.Car_OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_OrderField, value) != true)) {
                    this.Car_OrderField = value;
                    this.RaisePropertyChanged("Car_Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Order", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Order_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_ShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_RentalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_Start_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_End_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Order_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Order_IsCatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Order_DepositPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ActionService.Car_Checkout[] Car_CheckoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Order_User {
            get {
                return this.Order_UserField;
            }
            set {
                if ((this.Order_UserField.Equals(value) != true)) {
                    this.Order_UserField = value;
                    this.RaisePropertyChanged("Order_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Order_Shop {
            get {
                return this.Order_ShopField;
            }
            set {
                if ((this.Order_ShopField.Equals(value) != true)) {
                    this.Order_ShopField = value;
                    this.RaisePropertyChanged("Order_Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Order_Version {
            get {
                return this.Order_VersionField;
            }
            set {
                if ((this.Order_VersionField.Equals(value) != true)) {
                    this.Order_VersionField = value;
                    this.RaisePropertyChanged("Order_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Order_Count {
            get {
                return this.Order_CountField;
            }
            set {
                if ((this.Order_CountField.Equals(value) != true)) {
                    this.Order_CountField = value;
                    this.RaisePropertyChanged("Order_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Order_RentalType {
            get {
                return this.Order_RentalTypeField;
            }
            set {
                if ((this.Order_RentalTypeField.Equals(value) != true)) {
                    this.Order_RentalTypeField = value;
                    this.RaisePropertyChanged("Order_RentalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime Order_Start_Time {
            get {
                return this.Order_Start_TimeField;
            }
            set {
                if ((this.Order_Start_TimeField.Equals(value) != true)) {
                    this.Order_Start_TimeField = value;
                    this.RaisePropertyChanged("Order_Start_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime Order_End_Time {
            get {
                return this.Order_End_TimeField;
            }
            set {
                if ((this.Order_End_TimeField.Equals(value) != true)) {
                    this.Order_End_TimeField = value;
                    this.RaisePropertyChanged("Order_End_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Order_Action {
            get {
                return this.Order_ActionField;
            }
            set {
                if ((this.Order_ActionField.Equals(value) != true)) {
                    this.Order_ActionField = value;
                    this.RaisePropertyChanged("Order_Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Order_Message {
            get {
                return this.Order_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_MessageField, value) != true)) {
                    this.Order_MessageField = value;
                    this.RaisePropertyChanged("Order_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool Order_IsCatch {
            get {
                return this.Order_IsCatchField;
            }
            set {
                if ((this.Order_IsCatchField.Equals(value) != true)) {
                    this.Order_IsCatchField = value;
                    this.RaisePropertyChanged("Order_IsCatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool Order_DepositPay {
            get {
                return this.Order_DepositPayField;
            }
            set {
                if ((this.Order_DepositPayField.Equals(value) != true)) {
                    this.Order_DepositPayField = value;
                    this.RaisePropertyChanged("Order_DepositPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public MVCpart.ActionService.Car_Checkout[] Car_Checkout {
            get {
                return this.Car_CheckoutField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_CheckoutField, value) != true)) {
                    this.Car_CheckoutField = value;
                    this.RaisePropertyChanged("Car_Checkout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Checkout", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Checkout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> Checkout_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Checkout_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_KMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Checkout_MarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Checkout_ID {
            get {
                return this.Checkout_IDField;
            }
            set {
                if ((this.Checkout_IDField.Equals(value) != true)) {
                    this.Checkout_IDField = value;
                    this.RaisePropertyChanged("Checkout_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Checkout_Order {
            get {
                return this.Checkout_OrderField;
            }
            set {
                if ((this.Checkout_OrderField.Equals(value) != true)) {
                    this.Checkout_OrderField = value;
                    this.RaisePropertyChanged("Checkout_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Checkout_User {
            get {
                return this.Checkout_UserField;
            }
            set {
                if ((this.Checkout_UserField.Equals(value) != true)) {
                    this.Checkout_UserField = value;
                    this.RaisePropertyChanged("Checkout_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Checkout_Time {
            get {
                return this.Checkout_TimeField;
            }
            set {
                if ((this.Checkout_TimeField.Equals(value) != true)) {
                    this.Checkout_TimeField = value;
                    this.RaisePropertyChanged("Checkout_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Checkout_KM {
            get {
                return this.Checkout_KMField;
            }
            set {
                if ((this.Checkout_KMField.Equals(value) != true)) {
                    this.Checkout_KMField = value;
                    this.RaisePropertyChanged("Checkout_KM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Checkout_Mark {
            get {
                return this.Checkout_MarkField;
            }
            set {
                if ((this.Checkout_MarkField.Equals(value) != true)) {
                    this.Checkout_MarkField = value;
                    this.RaisePropertyChanged("Checkout_Mark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionService.IAction")]
    public interface IAction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/AddAction", ReplyAction="http://tempuri.org/IAction/AddActionResponse")]
        bool AddAction(MVCpart.ActionService.Car_Action Action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/DeleteAction", ReplyAction="http://tempuri.org/IAction/DeleteActionResponse")]
        bool DeleteAction(int ActionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/UpdateAction", ReplyAction="http://tempuri.org/IAction/UpdateActionResponse")]
        bool UpdateAction(MVCpart.ActionService.Car_Action TempAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/SelectAction_ID", ReplyAction="http://tempuri.org/IAction/SelectAction_IDResponse")]
        MVCpart.ActionService.Car_Action SelectAction_ID(int ActionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/SelectAllActions", ReplyAction="http://tempuri.org/IAction/SelectAllActionsResponse")]
        MVCpart.ActionService.Car_Action[] SelectAllActions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/SelectActionDIY_Func", ReplyAction="http://tempuri.org/IAction/SelectActionDIY_FuncResponse")]
        MVCpart.ActionService.Car_Action[] SelectActionDIY_Func(System.Func<MVCpart.ActionService.Car_Action, bool> where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAction/SelectActionDIY_Field", ReplyAction="http://tempuri.org/IAction/SelectActionDIY_FieldResponse")]
        MVCpart.ActionService.Car_Action[] SelectActionDIY_Field(System.Func<MVCpart.ActionService.Car_Action, bool> where, System.Func<MVCpart.ActionService.Car_Action, MVCpart.ActionService.Car_Action> select);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActionChannel : MVCpart.ActionService.IAction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActionClient : System.ServiceModel.ClientBase<MVCpart.ActionService.IAction>, MVCpart.ActionService.IAction {
        
        public ActionClient() {
        }
        
        public ActionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddAction(MVCpart.ActionService.Car_Action Action) {
            return base.Channel.AddAction(Action);
        }
        
        public bool DeleteAction(int ActionID) {
            return base.Channel.DeleteAction(ActionID);
        }
        
        public bool UpdateAction(MVCpart.ActionService.Car_Action TempAction) {
            return base.Channel.UpdateAction(TempAction);
        }
        
        public MVCpart.ActionService.Car_Action SelectAction_ID(int ActionID) {
            return base.Channel.SelectAction_ID(ActionID);
        }
        
        public MVCpart.ActionService.Car_Action[] SelectAllActions() {
            return base.Channel.SelectAllActions();
        }
        
        public MVCpart.ActionService.Car_Action[] SelectActionDIY_Func(System.Func<MVCpart.ActionService.Car_Action, bool> where) {
            return base.Channel.SelectActionDIY_Func(where);
        }
        
        public MVCpart.ActionService.Car_Action[] SelectActionDIY_Field(System.Func<MVCpart.ActionService.Car_Action, bool> where, System.Func<MVCpart.ActionService.Car_Action, MVCpart.ActionService.Car_Action> select) {
            return base.Channel.SelectActionDIY_Field(where, select);
        }
    }
}
