//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFpart.SalaryInfoSummeryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryInfo_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class SalaryInfo_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Salary_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Salary_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Salary_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredRoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Shop_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RAP_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SalaryAppend_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SalaryLog_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TatalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SalaryLog_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string User_Validation {
            get {
                return this.User_ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.User_ValidationField, value) != true)) {
                    this.User_ValidationField = value;
                    this.RaisePropertyChanged("User_Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string User_RealName {
            get {
                return this.User_RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_RealNameField, value) != true)) {
                    this.User_RealNameField = value;
                    this.RaisePropertyChanged("User_RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string User_Phone {
            get {
                return this.User_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PhoneField, value) != true)) {
                    this.User_PhoneField = value;
                    this.RaisePropertyChanged("User_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string User_Adress {
            get {
                return this.User_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.User_AdressField, value) != true)) {
                    this.User_AdressField = value;
                    this.RaisePropertyChanged("User_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string User_Info {
            get {
                return this.User_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.User_InfoField, value) != true)) {
                    this.User_InfoField = value;
                    this.RaisePropertyChanged("User_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Salary_ID {
            get {
                return this.Salary_IDField;
            }
            set {
                if ((this.Salary_IDField.Equals(value) != true)) {
                    this.Salary_IDField = value;
                    this.RaisePropertyChanged("Salary_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal Salary_Price {
            get {
                return this.Salary_PriceField;
            }
            set {
                if ((this.Salary_PriceField.Equals(value) != true)) {
                    this.Salary_PriceField = value;
                    this.RaisePropertyChanged("Salary_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Guid Salary_Role {
            get {
                return this.Salary_RoleField;
            }
            set {
                if ((this.Salary_RoleField.Equals(value) != true)) {
                    this.Salary_RoleField = value;
                    this.RaisePropertyChanged("Salary_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string LoweredRoleName {
            get {
                return this.LoweredRoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredRoleNameField, value) != true)) {
                    this.LoweredRoleNameField = value;
                    this.RaisePropertyChanged("LoweredRoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int Shop_ID {
            get {
                return this.Shop_IDField;
            }
            set {
                if ((this.Shop_IDField.Equals(value) != true)) {
                    this.Shop_IDField = value;
                    this.RaisePropertyChanged("Shop_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Shop_Phone {
            get {
                return this.Shop_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_PhoneField, value) != true)) {
                    this.Shop_PhoneField = value;
                    this.RaisePropertyChanged("Shop_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Shop_Name {
            get {
                return this.Shop_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_NameField, value) != true)) {
                    this.Shop_NameField = value;
                    this.RaisePropertyChanged("Shop_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<decimal> RAP_Price {
            get {
                return this.RAP_PriceField;
            }
            set {
                if ((this.RAP_PriceField.Equals(value) != true)) {
                    this.RAP_PriceField = value;
                    this.RaisePropertyChanged("RAP_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<decimal> SalaryAppend_Price {
            get {
                return this.SalaryAppend_PriceField;
            }
            set {
                if ((this.SalaryAppend_PriceField.Equals(value) != true)) {
                    this.SalaryAppend_PriceField = value;
                    this.RaisePropertyChanged("SalaryAppend_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<bool> SalaryLog_Mark {
            get {
                return this.SalaryLog_MarkField;
            }
            set {
                if ((this.SalaryLog_MarkField.Equals(value) != true)) {
                    this.SalaryLog_MarkField = value;
                    this.RaisePropertyChanged("SalaryLog_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<decimal> TatalPrice {
            get {
                return this.TatalPriceField;
            }
            set {
                if ((this.TatalPriceField.Equals(value) != true)) {
                    this.TatalPriceField = value;
                    this.RaisePropertyChanged("TatalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.Nullable<int> SalaryLog_ID {
            get {
                return this.SalaryLog_IDField;
            }
            set {
                if ((this.SalaryLog_IDField.Equals(value) != true)) {
                    this.SalaryLog_IDField = value;
                    this.RaisePropertyChanged("SalaryLog_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salary_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Salary_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Salary_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Salary_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Salary_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredRoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Salary_ID {
            get {
                return this.Salary_IDField;
            }
            set {
                if ((this.Salary_IDField.Equals(value) != true)) {
                    this.Salary_IDField = value;
                    this.RaisePropertyChanged("Salary_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Salary_Price {
            get {
                return this.Salary_PriceField;
            }
            set {
                if ((this.Salary_PriceField.Equals(value) != true)) {
                    this.Salary_PriceField = value;
                    this.RaisePropertyChanged("Salary_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Guid Salary_Role {
            get {
                return this.Salary_RoleField;
            }
            set {
                if ((this.Salary_RoleField.Equals(value) != true)) {
                    this.Salary_RoleField = value;
                    this.RaisePropertyChanged("Salary_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LoweredRoleName {
            get {
                return this.LoweredRoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredRoleNameField, value) != true)) {
                    this.LoweredRoleNameField = value;
                    this.RaisePropertyChanged("LoweredRoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RAP_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class RAP_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAP_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RAP_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid WorkRAP_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WorkRAP_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkRAP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RAP_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAP_Name {
            get {
                return this.RAP_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.RAP_NameField, value) != true)) {
                    this.RAP_NameField = value;
                    this.RaisePropertyChanged("RAP_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RAP_Price {
            get {
                return this.RAP_PriceField;
            }
            set {
                if ((this.RAP_PriceField.Equals(value) != true)) {
                    this.RAP_PriceField = value;
                    this.RaisePropertyChanged("RAP_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WorkRAP_User {
            get {
                return this.WorkRAP_UserField;
            }
            set {
                if ((this.WorkRAP_UserField.Equals(value) != true)) {
                    this.WorkRAP_UserField = value;
                    this.RaisePropertyChanged("WorkRAP_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime WorkRAP_Time {
            get {
                return this.WorkRAP_TimeField;
            }
            set {
                if ((this.WorkRAP_TimeField.Equals(value) != true)) {
                    this.WorkRAP_TimeField = value;
                    this.RaisePropertyChanged("WorkRAP_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string MobileAlias {
            get {
                return this.MobileAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileAliasField, value) != true)) {
                    this.MobileAliasField = value;
                    this.RaisePropertyChanged("MobileAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int WorkRAP_ID {
            get {
                return this.WorkRAP_IDField;
            }
            set {
                if ((this.WorkRAP_IDField.Equals(value) != true)) {
                    this.WorkRAP_IDField = value;
                    this.RaisePropertyChanged("WorkRAP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int RAP_ID {
            get {
                return this.RAP_IDField;
            }
            set {
                if ((this.RAP_IDField.Equals(value) != true)) {
                    this.RAP_IDField = value;
                    this.RaisePropertyChanged("RAP_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryAppend_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class SalaryAppend_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryAppend_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SalaryAppend_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryAppend_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SalaryAppend_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryAppend_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileAliasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaryAppend_ID {
            get {
                return this.SalaryAppend_IDField;
            }
            set {
                if ((this.SalaryAppend_IDField.Equals(value) != true)) {
                    this.SalaryAppend_IDField = value;
                    this.RaisePropertyChanged("SalaryAppend_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SalaryAppend_User {
            get {
                return this.SalaryAppend_UserField;
            }
            set {
                if ((this.SalaryAppend_UserField.Equals(value) != true)) {
                    this.SalaryAppend_UserField = value;
                    this.RaisePropertyChanged("SalaryAppend_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal SalaryAppend_Price {
            get {
                return this.SalaryAppend_PriceField;
            }
            set {
                if ((this.SalaryAppend_PriceField.Equals(value) != true)) {
                    this.SalaryAppend_PriceField = value;
                    this.RaisePropertyChanged("SalaryAppend_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime SalaryAppend_Time {
            get {
                return this.SalaryAppend_TimeField;
            }
            set {
                if ((this.SalaryAppend_TimeField.Equals(value) != true)) {
                    this.SalaryAppend_TimeField = value;
                    this.RaisePropertyChanged("SalaryAppend_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SalaryAppend_Info {
            get {
                return this.SalaryAppend_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryAppend_InfoField, value) != true)) {
                    this.SalaryAppend_InfoField = value;
                    this.RaisePropertyChanged("SalaryAppend_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string MobileAlias {
            get {
                return this.MobileAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileAliasField, value) != true)) {
                    this.MobileAliasField = value;
                    this.RaisePropertyChanged("MobileAlias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryInfoSummeryService.ISalaryInfoSummery")]
    public interface ISalaryInfoSummery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/SelectSalaryInfo", ReplyAction="http://tempuri.org/ISalaryInfoSummery/SelectSalaryInfoResponse")]
        WFpart.SalaryInfoSummeryService.SalaryInfo_ViewModel[] SelectSalaryInfo(System.Nullable<int> ShopID, string UserName, string RealName, string RoleName, System.Nullable<int> Year, System.Nullable<int> Month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/SelectAllSalary", ReplyAction="http://tempuri.org/ISalaryInfoSummery/SelectAllSalaryResponse")]
        WFpart.SalaryInfoSummeryService.Salary_ViewModel[] SelectAllSalary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/SelectAllRAP", ReplyAction="http://tempuri.org/ISalaryInfoSummery/SelectAllRAPResponse")]
        WFpart.SalaryInfoSummeryService.RAP_ViewModel[] SelectAllRAP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/SelectRAP_UID", ReplyAction="http://tempuri.org/ISalaryInfoSummery/SelectRAP_UIDResponse")]
        WFpart.SalaryInfoSummeryService.RAP_ViewModel[] SelectRAP_UID(System.Guid UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/SelectSalaryAppend", ReplyAction="http://tempuri.org/ISalaryInfoSummery/SelectSalaryAppendResponse")]
        WFpart.SalaryInfoSummeryService.SalaryAppend_ViewModel[] SelectSalaryAppend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/SelectSalaryAppend_UID", ReplyAction="http://tempuri.org/ISalaryInfoSummery/SelectSalaryAppend_UIDResponse")]
        WFpart.SalaryInfoSummeryService.SalaryAppend_ViewModel[] SelectSalaryAppend_UID(System.Guid UID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryInfoSummery/GetSalary", ReplyAction="http://tempuri.org/ISalaryInfoSummery/GetSalaryResponse")]
        bool GetSalary(int SalaryLogID, System.Guid UID, string RealName, decimal Price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryInfoSummeryChannel : WFpart.SalaryInfoSummeryService.ISalaryInfoSummery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryInfoSummeryClient : System.ServiceModel.ClientBase<WFpart.SalaryInfoSummeryService.ISalaryInfoSummery>, WFpart.SalaryInfoSummeryService.ISalaryInfoSummery {
        
        public SalaryInfoSummeryClient() {
        }
        
        public SalaryInfoSummeryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryInfoSummeryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryInfoSummeryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryInfoSummeryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WFpart.SalaryInfoSummeryService.SalaryInfo_ViewModel[] SelectSalaryInfo(System.Nullable<int> ShopID, string UserName, string RealName, string RoleName, System.Nullable<int> Year, System.Nullable<int> Month) {
            return base.Channel.SelectSalaryInfo(ShopID, UserName, RealName, RoleName, Year, Month);
        }
        
        public WFpart.SalaryInfoSummeryService.Salary_ViewModel[] SelectAllSalary() {
            return base.Channel.SelectAllSalary();
        }
        
        public WFpart.SalaryInfoSummeryService.RAP_ViewModel[] SelectAllRAP() {
            return base.Channel.SelectAllRAP();
        }
        
        public WFpart.SalaryInfoSummeryService.RAP_ViewModel[] SelectRAP_UID(System.Guid UID) {
            return base.Channel.SelectRAP_UID(UID);
        }
        
        public WFpart.SalaryInfoSummeryService.SalaryAppend_ViewModel[] SelectSalaryAppend() {
            return base.Channel.SelectSalaryAppend();
        }
        
        public WFpart.SalaryInfoSummeryService.SalaryAppend_ViewModel[] SelectSalaryAppend_UID(System.Guid UID) {
            return base.Channel.SelectSalaryAppend_UID(UID);
        }
        
        public bool GetSalary(int SalaryLogID, System.Guid UID, string RealName, decimal Price) {
            return base.Channel.GetSalary(SalaryLogID, UID, RealName, Price);
        }
    }
}
