//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCpart.OrderSummeryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Order_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Version_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Normal_RentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Member_RentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Normal_CatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Member_CatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_OverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_RidingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Over_RidingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_BaseKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Version_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Version_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Brand_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Brand_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Brand_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Brand_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Type_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Type_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Type_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Shop_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int City_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string City_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Province_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Province_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Action_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Action_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Action_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Action_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Client_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_MobileAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_ValidatonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Client_RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Client_RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> Staff_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_MobileAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Staff_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_Start_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_End_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Order_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Order_IsCatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalType_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RentalType_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Checkout_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_KMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Checkout_MarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version_ID {
            get {
                return this.Version_IDField;
            }
            set {
                if ((this.Version_IDField.Equals(value) != true)) {
                    this.Version_IDField = value;
                    this.RaisePropertyChanged("Version_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version_Name {
            get {
                return this.Version_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Version_NameField, value) != true)) {
                    this.Version_NameField = value;
                    this.RaisePropertyChanged("Version_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Version_Count {
            get {
                return this.Version_CountField;
            }
            set {
                if ((this.Version_CountField.Equals(value) != true)) {
                    this.Version_CountField = value;
                    this.RaisePropertyChanged("Version_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Version_Person {
            get {
                return this.Version_PersonField;
            }
            set {
                if ((this.Version_PersonField.Equals(value) != true)) {
                    this.Version_PersonField = value;
                    this.RaisePropertyChanged("Version_Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Version_Price_Normal_Rental {
            get {
                return this.Version_Price_Normal_RentalField;
            }
            set {
                if ((this.Version_Price_Normal_RentalField.Equals(value) != true)) {
                    this.Version_Price_Normal_RentalField = value;
                    this.RaisePropertyChanged("Version_Price_Normal_Rental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Version_Price_Member_Rental {
            get {
                return this.Version_Price_Member_RentalField;
            }
            set {
                if ((this.Version_Price_Member_RentalField.Equals(value) != true)) {
                    this.Version_Price_Member_RentalField = value;
                    this.RaisePropertyChanged("Version_Price_Member_Rental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal Version_Price_Normal_Catch {
            get {
                return this.Version_Price_Normal_CatchField;
            }
            set {
                if ((this.Version_Price_Normal_CatchField.Equals(value) != true)) {
                    this.Version_Price_Normal_CatchField = value;
                    this.RaisePropertyChanged("Version_Price_Normal_Catch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Version_Price_Member_Catch {
            get {
                return this.Version_Price_Member_CatchField;
            }
            set {
                if ((this.Version_Price_Member_CatchField.Equals(value) != true)) {
                    this.Version_Price_Member_CatchField = value;
                    this.RaisePropertyChanged("Version_Price_Member_Catch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal Version_Price_Over {
            get {
                return this.Version_Price_OverField;
            }
            set {
                if ((this.Version_Price_OverField.Equals(value) != true)) {
                    this.Version_Price_OverField = value;
                    this.RaisePropertyChanged("Version_Price_Over");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal Version_Price_Riding {
            get {
                return this.Version_Price_RidingField;
            }
            set {
                if ((this.Version_Price_RidingField.Equals(value) != true)) {
                    this.Version_Price_RidingField = value;
                    this.RaisePropertyChanged("Version_Price_Riding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal Version_Price_Over_Riding {
            get {
                return this.Version_Price_Over_RidingField;
            }
            set {
                if ((this.Version_Price_Over_RidingField.Equals(value) != true)) {
                    this.Version_Price_Over_RidingField = value;
                    this.RaisePropertyChanged("Version_Price_Over_Riding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public decimal Version_Price_Deposit {
            get {
                return this.Version_Price_DepositField;
            }
            set {
                if ((this.Version_Price_DepositField.Equals(value) != true)) {
                    this.Version_Price_DepositField = value;
                    this.RaisePropertyChanged("Version_Price_Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int Version_BaseKM {
            get {
                return this.Version_BaseKMField;
            }
            set {
                if ((this.Version_BaseKMField.Equals(value) != true)) {
                    this.Version_BaseKMField = value;
                    this.RaisePropertyChanged("Version_BaseKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Version_Info {
            get {
                return this.Version_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Version_InfoField, value) != true)) {
                    this.Version_InfoField = value;
                    this.RaisePropertyChanged("Version_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Version_IMG {
            get {
                return this.Version_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.Version_IMGField, value) != true)) {
                    this.Version_IMGField = value;
                    this.RaisePropertyChanged("Version_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int Brand_ID {
            get {
                return this.Brand_IDField;
            }
            set {
                if ((this.Brand_IDField.Equals(value) != true)) {
                    this.Brand_IDField = value;
                    this.RaisePropertyChanged("Brand_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Brand_Name {
            get {
                return this.Brand_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Brand_NameField, value) != true)) {
                    this.Brand_NameField = value;
                    this.RaisePropertyChanged("Brand_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string Brand_IMG {
            get {
                return this.Brand_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.Brand_IMGField, value) != true)) {
                    this.Brand_IMGField = value;
                    this.RaisePropertyChanged("Brand_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Brand_Info {
            get {
                return this.Brand_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Brand_InfoField, value) != true)) {
                    this.Brand_InfoField = value;
                    this.RaisePropertyChanged("Brand_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public int Type_ID {
            get {
                return this.Type_IDField;
            }
            set {
                if ((this.Type_IDField.Equals(value) != true)) {
                    this.Type_IDField = value;
                    this.RaisePropertyChanged("Type_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string Type_Name {
            get {
                return this.Type_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Type_NameField, value) != true)) {
                    this.Type_NameField = value;
                    this.RaisePropertyChanged("Type_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string Type_Info {
            get {
                return this.Type_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Type_InfoField, value) != true)) {
                    this.Type_InfoField = value;
                    this.RaisePropertyChanged("Type_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public int Shop_ID {
            get {
                return this.Shop_IDField;
            }
            set {
                if ((this.Shop_IDField.Equals(value) != true)) {
                    this.Shop_IDField = value;
                    this.RaisePropertyChanged("Shop_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string Shop_Name {
            get {
                return this.Shop_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_NameField, value) != true)) {
                    this.Shop_NameField = value;
                    this.RaisePropertyChanged("Shop_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string Shop_Phone {
            get {
                return this.Shop_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_PhoneField, value) != true)) {
                    this.Shop_PhoneField = value;
                    this.RaisePropertyChanged("Shop_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string Shop_Info {
            get {
                return this.Shop_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_InfoField, value) != true)) {
                    this.Shop_InfoField = value;
                    this.RaisePropertyChanged("Shop_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public int City_ID {
            get {
                return this.City_IDField;
            }
            set {
                if ((this.City_IDField.Equals(value) != true)) {
                    this.City_IDField = value;
                    this.RaisePropertyChanged("City_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string City_Name {
            get {
                return this.City_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.City_NameField, value) != true)) {
                    this.City_NameField = value;
                    this.RaisePropertyChanged("City_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public int Province_ID {
            get {
                return this.Province_IDField;
            }
            set {
                if ((this.Province_IDField.Equals(value) != true)) {
                    this.Province_IDField = value;
                    this.RaisePropertyChanged("Province_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string Province_Name {
            get {
                return this.Province_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Province_NameField, value) != true)) {
                    this.Province_NameField = value;
                    this.RaisePropertyChanged("Province_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public int Action_ID {
            get {
                return this.Action_IDField;
            }
            set {
                if ((this.Action_IDField.Equals(value) != true)) {
                    this.Action_IDField = value;
                    this.RaisePropertyChanged("Action_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string Action_Name {
            get {
                return this.Action_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Action_NameField, value) != true)) {
                    this.Action_NameField = value;
                    this.RaisePropertyChanged("Action_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public decimal Action_Price {
            get {
                return this.Action_PriceField;
            }
            set {
                if ((this.Action_PriceField.Equals(value) != true)) {
                    this.Action_PriceField = value;
                    this.RaisePropertyChanged("Action_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public string Action_Info {
            get {
                return this.Action_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Action_InfoField, value) != true)) {
                    this.Action_InfoField = value;
                    this.RaisePropertyChanged("Action_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public System.Guid Client_ID {
            get {
                return this.Client_IDField;
            }
            set {
                if ((this.Client_IDField.Equals(value) != true)) {
                    this.Client_IDField = value;
                    this.RaisePropertyChanged("Client_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string Client_UserName {
            get {
                return this.Client_UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_UserNameField, value) != true)) {
                    this.Client_UserNameField = value;
                    this.RaisePropertyChanged("Client_UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public string Client_LoweredUserName {
            get {
                return this.Client_LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_LoweredUserNameField, value) != true)) {
                    this.Client_LoweredUserNameField = value;
                    this.RaisePropertyChanged("Client_LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public string Client_MobileAlias {
            get {
                return this.Client_MobileAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_MobileAliasField, value) != true)) {
                    this.Client_MobileAliasField = value;
                    this.RaisePropertyChanged("Client_MobileAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public string Client_Validaton {
            get {
                return this.Client_ValidatonField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_ValidatonField, value) != true)) {
                    this.Client_ValidatonField = value;
                    this.RaisePropertyChanged("Client_Validaton");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public string Client_RealName {
            get {
                return this.Client_RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_RealNameField, value) != true)) {
                    this.Client_RealNameField = value;
                    this.RaisePropertyChanged("Client_RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string Client_Phone {
            get {
                return this.Client_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_PhoneField, value) != true)) {
                    this.Client_PhoneField = value;
                    this.RaisePropertyChanged("Client_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public string Client_Adress {
            get {
                return this.Client_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_AdressField, value) != true)) {
                    this.Client_AdressField = value;
                    this.RaisePropertyChanged("Client_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public string Client_Info {
            get {
                return this.Client_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_InfoField, value) != true)) {
                    this.Client_InfoField = value;
                    this.RaisePropertyChanged("Client_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public System.Guid Client_RoleID {
            get {
                return this.Client_RoleIDField;
            }
            set {
                if ((this.Client_RoleIDField.Equals(value) != true)) {
                    this.Client_RoleIDField = value;
                    this.RaisePropertyChanged("Client_RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public string Client_RoleName {
            get {
                return this.Client_RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Client_RoleNameField, value) != true)) {
                    this.Client_RoleNameField = value;
                    this.RaisePropertyChanged("Client_RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public System.Nullable<System.Guid> Staff_ID {
            get {
                return this.Staff_IDField;
            }
            set {
                if ((this.Staff_IDField.Equals(value) != true)) {
                    this.Staff_IDField = value;
                    this.RaisePropertyChanged("Staff_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public string Staff_UserName {
            get {
                return this.Staff_UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_UserNameField, value) != true)) {
                    this.Staff_UserNameField = value;
                    this.RaisePropertyChanged("Staff_UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public string Staff_LoweredUserName {
            get {
                return this.Staff_LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_LoweredUserNameField, value) != true)) {
                    this.Staff_LoweredUserNameField = value;
                    this.RaisePropertyChanged("Staff_LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public string Staff_MobileAlias {
            get {
                return this.Staff_MobileAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_MobileAliasField, value) != true)) {
                    this.Staff_MobileAliasField = value;
                    this.RaisePropertyChanged("Staff_MobileAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public string Staff_Validation {
            get {
                return this.Staff_ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_ValidationField, value) != true)) {
                    this.Staff_ValidationField = value;
                    this.RaisePropertyChanged("Staff_Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public string Staff_RealName {
            get {
                return this.Staff_RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_RealNameField, value) != true)) {
                    this.Staff_RealNameField = value;
                    this.RaisePropertyChanged("Staff_RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=51)]
        public string Staff_Phone {
            get {
                return this.Staff_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_PhoneField, value) != true)) {
                    this.Staff_PhoneField = value;
                    this.RaisePropertyChanged("Staff_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=52)]
        public string Staff_Adress {
            get {
                return this.Staff_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_AdressField, value) != true)) {
                    this.Staff_AdressField = value;
                    this.RaisePropertyChanged("Staff_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=53)]
        public string Staff_Info {
            get {
                return this.Staff_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Staff_InfoField, value) != true)) {
                    this.Staff_InfoField = value;
                    this.RaisePropertyChanged("Staff_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=54)]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=55)]
        public int Order_Count {
            get {
                return this.Order_CountField;
            }
            set {
                if ((this.Order_CountField.Equals(value) != true)) {
                    this.Order_CountField = value;
                    this.RaisePropertyChanged("Order_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=56)]
        public System.DateTime Order_Start_Time {
            get {
                return this.Order_Start_TimeField;
            }
            set {
                if ((this.Order_Start_TimeField.Equals(value) != true)) {
                    this.Order_Start_TimeField = value;
                    this.RaisePropertyChanged("Order_Start_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=57)]
        public System.DateTime Order_End_Time {
            get {
                return this.Order_End_TimeField;
            }
            set {
                if ((this.Order_End_TimeField.Equals(value) != true)) {
                    this.Order_End_TimeField = value;
                    this.RaisePropertyChanged("Order_End_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=58)]
        public string Order_Message {
            get {
                return this.Order_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_MessageField, value) != true)) {
                    this.Order_MessageField = value;
                    this.RaisePropertyChanged("Order_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=59)]
        public bool Order_IsCatch {
            get {
                return this.Order_IsCatchField;
            }
            set {
                if ((this.Order_IsCatchField.Equals(value) != true)) {
                    this.Order_IsCatchField = value;
                    this.RaisePropertyChanged("Order_IsCatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=60)]
        public int RentalType_ID {
            get {
                return this.RentalType_IDField;
            }
            set {
                if ((this.RentalType_IDField.Equals(value) != true)) {
                    this.RentalType_IDField = value;
                    this.RaisePropertyChanged("RentalType_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=61)]
        public string RentalType_Name {
            get {
                return this.RentalType_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalType_NameField, value) != true)) {
                    this.RentalType_NameField = value;
                    this.RaisePropertyChanged("RentalType_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=62)]
        public int Checkout_ID {
            get {
                return this.Checkout_IDField;
            }
            set {
                if ((this.Checkout_IDField.Equals(value) != true)) {
                    this.Checkout_IDField = value;
                    this.RaisePropertyChanged("Checkout_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=63)]
        public System.DateTime Checkout_Time {
            get {
                return this.Checkout_TimeField;
            }
            set {
                if ((this.Checkout_TimeField.Equals(value) != true)) {
                    this.Checkout_TimeField = value;
                    this.RaisePropertyChanged("Checkout_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=64)]
        public int Checkout_KM {
            get {
                return this.Checkout_KMField;
            }
            set {
                if ((this.Checkout_KMField.Equals(value) != true)) {
                    this.Checkout_KMField = value;
                    this.RaisePropertyChanged("Checkout_KM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=65)]
        public bool Checkout_Mark {
            get {
                return this.Checkout_MarkField;
            }
            set {
                if ((this.Checkout_MarkField.Equals(value) != true)) {
                    this.Checkout_MarkField = value;
                    this.RaisePropertyChanged("Checkout_Mark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderSummeryService.IOrderSummery")]
    public interface IOrderSummery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectOrderSummery_OrderID", ReplyAction="http://tempuri.org/IOrderSummery/SelectOrderSummery_OrderIDResponse")]
        MVCpart.OrderSummeryService.Order_ViewModel SelectOrderSummery_OrderID(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/GetPrice_Order", ReplyAction="http://tempuri.org/IOrderSummery/GetPrice_OrderResponse")]
        decimal GetPrice_Order(MVCpart.OrderSummeryService.Order_ViewModel Summery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/GetPrice_OrderID", ReplyAction="http://tempuri.org/IOrderSummery/GetPrice_OrderIDResponse")]
        decimal GetPrice_OrderID(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/Pay_Order", ReplyAction="http://tempuri.org/IOrderSummery/Pay_OrderResponse")]
        bool Pay_Order(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/LastCheakOrder", ReplyAction="http://tempuri.org/IOrderSummery/LastCheakOrderResponse")]
        bool LastCheakOrder(string StaffName, int OrderID, int KM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectOrderSummery_ClientName", ReplyAction="http://tempuri.org/IOrderSummery/SelectOrderSummery_ClientNameResponse")]
        MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummery_ClientName(string ClientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectOrderSummery_StaffName", ReplyAction="http://tempuri.org/IOrderSummery/SelectOrderSummery_StaffNameResponse")]
        MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummery_StaffName(string StaffName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectOrderSummerys_CarVersion", ReplyAction="http://tempuri.org/IOrderSummery/SelectOrderSummerys_CarVersionResponse")]
        MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummerys_CarVersion(int VersionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectOrderSummerys_ShopID", ReplyAction="http://tempuri.org/IOrderSummery/SelectOrderSummerys_ShopIDResponse")]
        MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummerys_ShopID(int ShopID, System.Nullable<int> year, System.Nullable<int> month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectOrderSummerys_Time", ReplyAction="http://tempuri.org/IOrderSummery/SelectOrderSummerys_TimeResponse")]
        MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummerys_Time(System.Nullable<int> Year, System.Nullable<int> Month, System.Nullable<int> Day, System.Nullable<bool> Ispay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/SelectRentaledCarCount_TimeAndVersion", ReplyAction="http://tempuri.org/IOrderSummery/SelectRentaledCarCount_TimeAndVersionResponse")]
        int SelectRentaledCarCount_TimeAndVersion(int ShopID, int VersionID, System.Nullable<int> StartYear, System.Nullable<int> StartMonth, System.Nullable<int> StartDay, System.Nullable<int> EndYear, System.Nullable<int> EndMonth, System.Nullable<int> EndDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderSummery/Order_Cancel", ReplyAction="http://tempuri.org/IOrderSummery/Order_CancelResponse")]
        bool Order_Cancel(int OrderID, System.Guid UID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderSummeryChannel : MVCpart.OrderSummeryService.IOrderSummery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderSummeryClient : System.ServiceModel.ClientBase<MVCpart.OrderSummeryService.IOrderSummery>, MVCpart.OrderSummeryService.IOrderSummery {
        
        public OrderSummeryClient() {
        }
        
        public OrderSummeryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderSummeryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderSummeryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderSummeryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCpart.OrderSummeryService.Order_ViewModel SelectOrderSummery_OrderID(int OrderID) {
            return base.Channel.SelectOrderSummery_OrderID(OrderID);
        }
        
        public decimal GetPrice_Order(MVCpart.OrderSummeryService.Order_ViewModel Summery) {
            return base.Channel.GetPrice_Order(Summery);
        }
        
        public decimal GetPrice_OrderID(int OrderID) {
            return base.Channel.GetPrice_OrderID(OrderID);
        }
        
        public bool Pay_Order(int OrderID) {
            return base.Channel.Pay_Order(OrderID);
        }
        
        public bool LastCheakOrder(string StaffName, int OrderID, int KM) {
            return base.Channel.LastCheakOrder(StaffName, OrderID, KM);
        }
        
        public MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummery_ClientName(string ClientName) {
            return base.Channel.SelectOrderSummery_ClientName(ClientName);
        }
        
        public MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummery_StaffName(string StaffName) {
            return base.Channel.SelectOrderSummery_StaffName(StaffName);
        }
        
        public MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummerys_CarVersion(int VersionID) {
            return base.Channel.SelectOrderSummerys_CarVersion(VersionID);
        }
        
        public MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummerys_ShopID(int ShopID, System.Nullable<int> year, System.Nullable<int> month) {
            return base.Channel.SelectOrderSummerys_ShopID(ShopID, year, month);
        }
        
        public MVCpart.OrderSummeryService.Order_ViewModel[] SelectOrderSummerys_Time(System.Nullable<int> Year, System.Nullable<int> Month, System.Nullable<int> Day, System.Nullable<bool> Ispay) {
            return base.Channel.SelectOrderSummerys_Time(Year, Month, Day, Ispay);
        }
        
        public int SelectRentaledCarCount_TimeAndVersion(int ShopID, int VersionID, System.Nullable<int> StartYear, System.Nullable<int> StartMonth, System.Nullable<int> StartDay, System.Nullable<int> EndYear, System.Nullable<int> EndMonth, System.Nullable<int> EndDay) {
            return base.Channel.SelectRentaledCarCount_TimeAndVersion(ShopID, VersionID, StartYear, StartMonth, StartDay, EndYear, EndMonth, EndDay);
        }
        
        public bool Order_Cancel(int OrderID, System.Guid UID) {
            return base.Channel.Order_Cancel(OrderID, UID);
        }
    }
}
