//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCpart.ShopService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Shop", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Shop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Shop_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Shop_CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ShopService.Car_Account[] Car_AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ShopService.Car_Version[] Car_VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ShopService.UserInShop[] UserInShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ShopService.Car_Order[] Car_OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shop_ID {
            get {
                return this.Shop_IDField;
            }
            set {
                if ((this.Shop_IDField.Equals(value) != true)) {
                    this.Shop_IDField = value;
                    this.RaisePropertyChanged("Shop_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shop_Name {
            get {
                return this.Shop_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_NameField, value) != true)) {
                    this.Shop_NameField = value;
                    this.RaisePropertyChanged("Shop_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shop_Phone {
            get {
                return this.Shop_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_PhoneField, value) != true)) {
                    this.Shop_PhoneField = value;
                    this.RaisePropertyChanged("Shop_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Shop_City {
            get {
                return this.Shop_CityField;
            }
            set {
                if ((this.Shop_CityField.Equals(value) != true)) {
                    this.Shop_CityField = value;
                    this.RaisePropertyChanged("Shop_City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Shop_Info {
            get {
                return this.Shop_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_InfoField, value) != true)) {
                    this.Shop_InfoField = value;
                    this.RaisePropertyChanged("Shop_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public MVCpart.ShopService.Car_Account[] Car_Account {
            get {
                return this.Car_AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_AccountField, value) != true)) {
                    this.Car_AccountField = value;
                    this.RaisePropertyChanged("Car_Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public MVCpart.ShopService.Car_Version[] Car_Version {
            get {
                return this.Car_VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_VersionField, value) != true)) {
                    this.Car_VersionField = value;
                    this.RaisePropertyChanged("Car_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public MVCpart.ShopService.UserInShop[] UserInShop {
            get {
                return this.UserInShopField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInShopField, value) != true)) {
                    this.UserInShopField = value;
                    this.RaisePropertyChanged("UserInShop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public MVCpart.ShopService.Car_Order[] Car_Order {
            get {
                return this.Car_OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_OrderField, value) != true)) {
                    this.Car_OrderField = value;
                    this.RaisePropertyChanged("Car_Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Account", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Account_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Account_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Account_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Account_ShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Account_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Account_InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Account_ID {
            get {
                return this.Account_IDField;
            }
            set {
                if ((this.Account_IDField.Equals(value) != true)) {
                    this.Account_IDField = value;
                    this.RaisePropertyChanged("Account_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Account_Price {
            get {
                return this.Account_PriceField;
            }
            set {
                if ((this.Account_PriceField.Equals(value) != true)) {
                    this.Account_PriceField = value;
                    this.RaisePropertyChanged("Account_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Account_User {
            get {
                return this.Account_UserField;
            }
            set {
                if ((this.Account_UserField.Equals(value) != true)) {
                    this.Account_UserField = value;
                    this.RaisePropertyChanged("Account_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Account_Shop {
            get {
                return this.Account_ShopField;
            }
            set {
                if ((this.Account_ShopField.Equals(value) != true)) {
                    this.Account_ShopField = value;
                    this.RaisePropertyChanged("Account_Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime Account_Time {
            get {
                return this.Account_TimeField;
            }
            set {
                if ((this.Account_TimeField.Equals(value) != true)) {
                    this.Account_TimeField = value;
                    this.RaisePropertyChanged("Account_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Account_Info {
            get {
                return this.Account_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Account_InfoField, value) != true)) {
                    this.Account_InfoField = value;
                    this.RaisePropertyChanged("Account_Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Version", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Version : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Version_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_ShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Normal_RentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Member_RentalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Normal_CatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Member_CatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_OverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_RidingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_Over_RidingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Version_Price_DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Version_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Version_IMGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Version_BaseKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ShopService.Car_Order[] Car_OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version_ID {
            get {
                return this.Version_IDField;
            }
            set {
                if ((this.Version_IDField.Equals(value) != true)) {
                    this.Version_IDField = value;
                    this.RaisePropertyChanged("Version_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version_Name {
            get {
                return this.Version_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Version_NameField, value) != true)) {
                    this.Version_NameField = value;
                    this.RaisePropertyChanged("Version_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Version_Count {
            get {
                return this.Version_CountField;
            }
            set {
                if ((this.Version_CountField.Equals(value) != true)) {
                    this.Version_CountField = value;
                    this.RaisePropertyChanged("Version_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Version_Person {
            get {
                return this.Version_PersonField;
            }
            set {
                if ((this.Version_PersonField.Equals(value) != true)) {
                    this.Version_PersonField = value;
                    this.RaisePropertyChanged("Version_Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Version_Type {
            get {
                return this.Version_TypeField;
            }
            set {
                if ((this.Version_TypeField.Equals(value) != true)) {
                    this.Version_TypeField = value;
                    this.RaisePropertyChanged("Version_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Version_Brand {
            get {
                return this.Version_BrandField;
            }
            set {
                if ((this.Version_BrandField.Equals(value) != true)) {
                    this.Version_BrandField = value;
                    this.RaisePropertyChanged("Version_Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Version_Shop {
            get {
                return this.Version_ShopField;
            }
            set {
                if ((this.Version_ShopField.Equals(value) != true)) {
                    this.Version_ShopField = value;
                    this.RaisePropertyChanged("Version_Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal Version_Price_Normal_Rental {
            get {
                return this.Version_Price_Normal_RentalField;
            }
            set {
                if ((this.Version_Price_Normal_RentalField.Equals(value) != true)) {
                    this.Version_Price_Normal_RentalField = value;
                    this.RaisePropertyChanged("Version_Price_Normal_Rental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal Version_Price_Member_Rental {
            get {
                return this.Version_Price_Member_RentalField;
            }
            set {
                if ((this.Version_Price_Member_RentalField.Equals(value) != true)) {
                    this.Version_Price_Member_RentalField = value;
                    this.RaisePropertyChanged("Version_Price_Member_Rental");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal Version_Price_Normal_Catch {
            get {
                return this.Version_Price_Normal_CatchField;
            }
            set {
                if ((this.Version_Price_Normal_CatchField.Equals(value) != true)) {
                    this.Version_Price_Normal_CatchField = value;
                    this.RaisePropertyChanged("Version_Price_Normal_Catch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal Version_Price_Member_Catch {
            get {
                return this.Version_Price_Member_CatchField;
            }
            set {
                if ((this.Version_Price_Member_CatchField.Equals(value) != true)) {
                    this.Version_Price_Member_CatchField = value;
                    this.RaisePropertyChanged("Version_Price_Member_Catch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public decimal Version_Price_Over {
            get {
                return this.Version_Price_OverField;
            }
            set {
                if ((this.Version_Price_OverField.Equals(value) != true)) {
                    this.Version_Price_OverField = value;
                    this.RaisePropertyChanged("Version_Price_Over");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public decimal Version_Price_Riding {
            get {
                return this.Version_Price_RidingField;
            }
            set {
                if ((this.Version_Price_RidingField.Equals(value) != true)) {
                    this.Version_Price_RidingField = value;
                    this.RaisePropertyChanged("Version_Price_Riding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public decimal Version_Price_Over_Riding {
            get {
                return this.Version_Price_Over_RidingField;
            }
            set {
                if ((this.Version_Price_Over_RidingField.Equals(value) != true)) {
                    this.Version_Price_Over_RidingField = value;
                    this.RaisePropertyChanged("Version_Price_Over_Riding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public decimal Version_Price_Deposit {
            get {
                return this.Version_Price_DepositField;
            }
            set {
                if ((this.Version_Price_DepositField.Equals(value) != true)) {
                    this.Version_Price_DepositField = value;
                    this.RaisePropertyChanged("Version_Price_Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Version_Info {
            get {
                return this.Version_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Version_InfoField, value) != true)) {
                    this.Version_InfoField = value;
                    this.RaisePropertyChanged("Version_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Version_IMG {
            get {
                return this.Version_IMGField;
            }
            set {
                if ((object.ReferenceEquals(this.Version_IMGField, value) != true)) {
                    this.Version_IMGField = value;
                    this.RaisePropertyChanged("Version_IMG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public int Version_BaseKM {
            get {
                return this.Version_BaseKMField;
            }
            set {
                if ((this.Version_BaseKMField.Equals(value) != true)) {
                    this.Version_BaseKMField = value;
                    this.RaisePropertyChanged("Version_BaseKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public MVCpart.ShopService.Car_Order[] Car_Order {
            get {
                return this.Car_OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_OrderField, value) != true)) {
                    this.Car_OrderField = value;
                    this.RaisePropertyChanged("Car_Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInShop", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class UserInShop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShopIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ShopID {
            get {
                return this.ShopIDField;
            }
            set {
                if ((this.ShopIDField.Equals(value) != true)) {
                    this.ShopIDField = value;
                    this.RaisePropertyChanged("ShopID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Order", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid Order_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_ShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_RentalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_Start_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Order_End_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Order_MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Order_IsCatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Order_DepositPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCpart.ShopService.Car_Checkout[] Car_CheckoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Order_User {
            get {
                return this.Order_UserField;
            }
            set {
                if ((this.Order_UserField.Equals(value) != true)) {
                    this.Order_UserField = value;
                    this.RaisePropertyChanged("Order_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Order_Shop {
            get {
                return this.Order_ShopField;
            }
            set {
                if ((this.Order_ShopField.Equals(value) != true)) {
                    this.Order_ShopField = value;
                    this.RaisePropertyChanged("Order_Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Order_Version {
            get {
                return this.Order_VersionField;
            }
            set {
                if ((this.Order_VersionField.Equals(value) != true)) {
                    this.Order_VersionField = value;
                    this.RaisePropertyChanged("Order_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Order_Count {
            get {
                return this.Order_CountField;
            }
            set {
                if ((this.Order_CountField.Equals(value) != true)) {
                    this.Order_CountField = value;
                    this.RaisePropertyChanged("Order_Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Order_RentalType {
            get {
                return this.Order_RentalTypeField;
            }
            set {
                if ((this.Order_RentalTypeField.Equals(value) != true)) {
                    this.Order_RentalTypeField = value;
                    this.RaisePropertyChanged("Order_RentalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime Order_Start_Time {
            get {
                return this.Order_Start_TimeField;
            }
            set {
                if ((this.Order_Start_TimeField.Equals(value) != true)) {
                    this.Order_Start_TimeField = value;
                    this.RaisePropertyChanged("Order_Start_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime Order_End_Time {
            get {
                return this.Order_End_TimeField;
            }
            set {
                if ((this.Order_End_TimeField.Equals(value) != true)) {
                    this.Order_End_TimeField = value;
                    this.RaisePropertyChanged("Order_End_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Order_Action {
            get {
                return this.Order_ActionField;
            }
            set {
                if ((this.Order_ActionField.Equals(value) != true)) {
                    this.Order_ActionField = value;
                    this.RaisePropertyChanged("Order_Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Order_Message {
            get {
                return this.Order_MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.Order_MessageField, value) != true)) {
                    this.Order_MessageField = value;
                    this.RaisePropertyChanged("Order_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool Order_IsCatch {
            get {
                return this.Order_IsCatchField;
            }
            set {
                if ((this.Order_IsCatchField.Equals(value) != true)) {
                    this.Order_IsCatchField = value;
                    this.RaisePropertyChanged("Order_IsCatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool Order_DepositPay {
            get {
                return this.Order_DepositPayField;
            }
            set {
                if ((this.Order_DepositPayField.Equals(value) != true)) {
                    this.Order_DepositPayField = value;
                    this.RaisePropertyChanged("Order_DepositPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public MVCpart.ShopService.Car_Checkout[] Car_Checkout {
            get {
                return this.Car_CheckoutField;
            }
            set {
                if ((object.ReferenceEquals(this.Car_CheckoutField, value) != true)) {
                    this.Car_CheckoutField = value;
                    this.RaisePropertyChanged("Car_Checkout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Checkout", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Checkout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> Checkout_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Checkout_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Checkout_KMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Checkout_MarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Checkout_ID {
            get {
                return this.Checkout_IDField;
            }
            set {
                if ((this.Checkout_IDField.Equals(value) != true)) {
                    this.Checkout_IDField = value;
                    this.RaisePropertyChanged("Checkout_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Checkout_Order {
            get {
                return this.Checkout_OrderField;
            }
            set {
                if ((this.Checkout_OrderField.Equals(value) != true)) {
                    this.Checkout_OrderField = value;
                    this.RaisePropertyChanged("Checkout_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Checkout_User {
            get {
                return this.Checkout_UserField;
            }
            set {
                if ((this.Checkout_UserField.Equals(value) != true)) {
                    this.Checkout_UserField = value;
                    this.RaisePropertyChanged("Checkout_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Checkout_Time {
            get {
                return this.Checkout_TimeField;
            }
            set {
                if ((this.Checkout_TimeField.Equals(value) != true)) {
                    this.Checkout_TimeField = value;
                    this.RaisePropertyChanged("Checkout_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Checkout_KM {
            get {
                return this.Checkout_KMField;
            }
            set {
                if ((this.Checkout_KMField.Equals(value) != true)) {
                    this.Checkout_KMField = value;
                    this.RaisePropertyChanged("Checkout_KM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Checkout_Mark {
            get {
                return this.Checkout_MarkField;
            }
            set {
                if ((this.Checkout_MarkField.Equals(value) != true)) {
                    this.Checkout_MarkField = value;
                    this.RaisePropertyChanged("Checkout_Mark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShopService.IShop")]
    public interface IShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddShop", ReplyAction="http://tempuri.org/IShop/AddShopResponse")]
        bool AddShop(MVCpart.ShopService.Car_Shop Shop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/DeleteShop", ReplyAction="http://tempuri.org/IShop/DeleteShopResponse")]
        bool DeleteShop(int ShopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/UpdateShop", ReplyAction="http://tempuri.org/IShop/UpdateShopResponse")]
        bool UpdateShop(MVCpart.ShopService.Car_Shop TempShop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SelectShop_ID", ReplyAction="http://tempuri.org/IShop/SelectShop_IDResponse")]
        MVCpart.ShopService.Car_Shop SelectShop_ID(int ShopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SelectShop_Name", ReplyAction="http://tempuri.org/IShop/SelectShop_NameResponse")]
        MVCpart.ShopService.Car_Shop SelectShop_Name(string ShopName, int CityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SelectShop_CityID", ReplyAction="http://tempuri.org/IShop/SelectShop_CityIDResponse")]
        MVCpart.ShopService.Car_Shop[] SelectShop_CityID(int CityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SelectAllShops", ReplyAction="http://tempuri.org/IShop/SelectAllShopsResponse")]
        MVCpart.ShopService.Car_Shop[] SelectAllShops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SelectShopDIY_Func", ReplyAction="http://tempuri.org/IShop/SelectShopDIY_FuncResponse")]
        MVCpart.ShopService.Car_Shop[] SelectShopDIY_Func(System.Func<MVCpart.ShopService.Car_Shop, bool> where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/SelectShopDIY_Field", ReplyAction="http://tempuri.org/IShop/SelectShopDIY_FieldResponse")]
        MVCpart.ShopService.Car_Shop[] SelectShopDIY_Field(System.Func<MVCpart.ShopService.Car_Shop, bool> where, System.Func<MVCpart.ShopService.Car_Shop, MVCpart.ShopService.Car_Shop> select);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopChannel : MVCpart.ShopService.IShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopClient : System.ServiceModel.ClientBase<MVCpart.ShopService.IShop>, MVCpart.ShopService.IShop {
        
        public ShopClient() {
        }
        
        public ShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddShop(MVCpart.ShopService.Car_Shop Shop) {
            return base.Channel.AddShop(Shop);
        }
        
        public bool DeleteShop(int ShopID) {
            return base.Channel.DeleteShop(ShopID);
        }
        
        public bool UpdateShop(MVCpart.ShopService.Car_Shop TempShop) {
            return base.Channel.UpdateShop(TempShop);
        }
        
        public MVCpart.ShopService.Car_Shop SelectShop_ID(int ShopID) {
            return base.Channel.SelectShop_ID(ShopID);
        }
        
        public MVCpart.ShopService.Car_Shop SelectShop_Name(string ShopName, int CityID) {
            return base.Channel.SelectShop_Name(ShopName, CityID);
        }
        
        public MVCpart.ShopService.Car_Shop[] SelectShop_CityID(int CityID) {
            return base.Channel.SelectShop_CityID(CityID);
        }
        
        public MVCpart.ShopService.Car_Shop[] SelectAllShops() {
            return base.Channel.SelectAllShops();
        }
        
        public MVCpart.ShopService.Car_Shop[] SelectShopDIY_Func(System.Func<MVCpart.ShopService.Car_Shop, bool> where) {
            return base.Channel.SelectShopDIY_Func(where);
        }
        
        public MVCpart.ShopService.Car_Shop[] SelectShopDIY_Field(System.Func<MVCpart.ShopService.Car_Shop, bool> where, System.Func<MVCpart.ShopService.Car_Shop, MVCpart.ShopService.Car_Shop> select) {
            return base.Channel.SelectShopDIY_Field(where, select);
        }
    }
}
