//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCpart.UserManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart.SOA.EndPoint")]
    [System.SerializableAttribute()]
    public partial class User_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_UsersEX", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class aspnet_UsersEX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Validation {
            get {
                return this.User_ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.User_ValidationField, value) != true)) {
                    this.User_ValidationField = value;
                    this.RaisePropertyChanged("User_Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string User_RealName {
            get {
                return this.User_RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_RealNameField, value) != true)) {
                    this.User_RealNameField = value;
                    this.RaisePropertyChanged("User_RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string User_Phone {
            get {
                return this.User_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PhoneField, value) != true)) {
                    this.User_PhoneField = value;
                    this.RaisePropertyChanged("User_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string User_Adress {
            get {
                return this.User_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.User_AdressField, value) != true)) {
                    this.User_AdressField = value;
                    this.RaisePropertyChanged("User_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string User_Info {
            get {
                return this.User_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.User_InfoField, value) != true)) {
                    this.User_InfoField = value;
                    this.RaisePropertyChanged("User_Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Shop_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Province_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Province_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int City_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string City_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Shop_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Shop_InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Province_ID {
            get {
                return this.Province_IDField;
            }
            set {
                if ((this.Province_IDField.Equals(value) != true)) {
                    this.Province_IDField = value;
                    this.RaisePropertyChanged("Province_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province_Name {
            get {
                return this.Province_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Province_NameField, value) != true)) {
                    this.Province_NameField = value;
                    this.RaisePropertyChanged("Province_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int City_ID {
            get {
                return this.City_IDField;
            }
            set {
                if ((this.City_IDField.Equals(value) != true)) {
                    this.City_IDField = value;
                    this.RaisePropertyChanged("City_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string City_Name {
            get {
                return this.City_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.City_NameField, value) != true)) {
                    this.City_NameField = value;
                    this.RaisePropertyChanged("City_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Shop_ID {
            get {
                return this.Shop_IDField;
            }
            set {
                if ((this.Shop_IDField.Equals(value) != true)) {
                    this.Shop_IDField = value;
                    this.RaisePropertyChanged("Shop_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Shop_Name {
            get {
                return this.Shop_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_NameField, value) != true)) {
                    this.Shop_NameField = value;
                    this.RaisePropertyChanged("Shop_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Shop_Phone {
            get {
                return this.Shop_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_PhoneField, value) != true)) {
                    this.Shop_PhoneField = value;
                    this.RaisePropertyChanged("Shop_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Shop_Info {
            get {
                return this.Shop_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.Shop_InfoField, value) != true)) {
                    this.Shop_InfoField = value;
                    this.RaisePropertyChanged("Shop_Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<System.Guid> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagerService.IUserManager")]
    public interface IUserManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserReg", ReplyAction="http://tempuri.org/IUserManager/UserRegResponse")]
        bool UserReg(MVCpart.UserManagerService.User_ViewModel User, MVCpart.UserManagerService.aspnet_UsersEX UserEX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/RoleCreat", ReplyAction="http://tempuri.org/IUserManager/RoleCreatResponse")]
        void RoleCreat(string RoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/RoleSelectAll", ReplyAction="http://tempuri.org/IUserManager/RoleSelectAllResponse")]
        string[] RoleSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserPutInRole", ReplyAction="http://tempuri.org/IUserManager/UserPutInRoleResponse")]
        bool UserPutInRole(string UserName, string RoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserSelectAll", ReplyAction="http://tempuri.org/IUserManager/UserSelectAllResponse")]
        string[] UserSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserSelect_RoleName", ReplyAction="http://tempuri.org/IUserManager/UserSelect_RoleNameResponse")]
        string[] UserSelect_RoleName(string RoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/RoleSelect_UserName", ReplyAction="http://tempuri.org/IUserManager/RoleSelect_UserNameResponse")]
        string[] RoleSelect_UserName(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/RoleUserDelete", ReplyAction="http://tempuri.org/IUserManager/RoleUserDeleteResponse")]
        bool RoleUserDelete(string UserName, string RoleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/GetAllShops", ReplyAction="http://tempuri.org/IUserManager/GetAllShopsResponse")]
        MVCpart.UserManagerService.Shop_ViewModel[] GetAllShops(System.Nullable<int> ProvinceID, System.Nullable<int> CityID, System.Nullable<int> ShopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserPutInShop", ReplyAction="http://tempuri.org/IUserManager/UserPutInShopResponse")]
        bool UserPutInShop(System.Guid UserID, int ShopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserDropShop_UserID", ReplyAction="http://tempuri.org/IUserManager/UserDropShop_UserIDResponse")]
        bool UserDropShop_UserID(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserDropShop_ShopID", ReplyAction="http://tempuri.org/IUserManager/UserDropShop_ShopIDResponse")]
        bool UserDropShop_ShopID(int ShopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserChangeShop", ReplyAction="http://tempuri.org/IUserManager/UserChangeShopResponse")]
        bool UserChangeShop(System.Guid UserID, int ShopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/SelectShopID_UserID", ReplyAction="http://tempuri.org/IUserManager/SelectShopID_UserIDResponse")]
        int SelectShopID_UserID(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserUpdate_NoOldPassword", ReplyAction="http://tempuri.org/IUserManager/UserUpdate_NoOldPasswordResponse")]
        bool UserUpdate_NoOldPassword(string UserName, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserAQUpdate_NoOldPassword", ReplyAction="http://tempuri.org/IUserManager/UserAQUpdate_NoOldPasswordResponse")]
        bool UserAQUpdate_NoOldPassword(string UserName, string Question, string Answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/SelectUserEXInfo_All", ReplyAction="http://tempuri.org/IUserManager/SelectUserEXInfo_AllResponse")]
        MVCpart.UserManagerService.aspnet_UsersEX[] SelectUserEXInfo_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/SelectUserInfo_All", ReplyAction="http://tempuri.org/IUserManager/SelectUserInfo_AllResponse")]
        MVCpart.UserManagerService.User_ViewModel[] SelectUserInfo_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/DropUser", ReplyAction="http://tempuri.org/IUserManager/DropUserResponse")]
        bool DropUser(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/UserEXUpdate", ReplyAction="http://tempuri.org/IUserManager/UserEXUpdateResponse")]
        bool UserEXUpdate(MVCpart.UserManagerService.aspnet_UsersEX TempUserEX);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerChannel : MVCpart.UserManagerService.IUserManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerClient : System.ServiceModel.ClientBase<MVCpart.UserManagerService.IUserManager>, MVCpart.UserManagerService.IUserManager {
        
        public UserManagerClient() {
        }
        
        public UserManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UserReg(MVCpart.UserManagerService.User_ViewModel User, MVCpart.UserManagerService.aspnet_UsersEX UserEX) {
            return base.Channel.UserReg(User, UserEX);
        }
        
        public void RoleCreat(string RoleName) {
            base.Channel.RoleCreat(RoleName);
        }
        
        public string[] RoleSelectAll() {
            return base.Channel.RoleSelectAll();
        }
        
        public bool UserPutInRole(string UserName, string RoleName) {
            return base.Channel.UserPutInRole(UserName, RoleName);
        }
        
        public string[] UserSelectAll() {
            return base.Channel.UserSelectAll();
        }
        
        public string[] UserSelect_RoleName(string RoleName) {
            return base.Channel.UserSelect_RoleName(RoleName);
        }
        
        public string[] RoleSelect_UserName(string UserName) {
            return base.Channel.RoleSelect_UserName(UserName);
        }
        
        public bool RoleUserDelete(string UserName, string RoleName) {
            return base.Channel.RoleUserDelete(UserName, RoleName);
        }
        
        public MVCpart.UserManagerService.Shop_ViewModel[] GetAllShops(System.Nullable<int> ProvinceID, System.Nullable<int> CityID, System.Nullable<int> ShopID) {
            return base.Channel.GetAllShops(ProvinceID, CityID, ShopID);
        }
        
        public bool UserPutInShop(System.Guid UserID, int ShopID) {
            return base.Channel.UserPutInShop(UserID, ShopID);
        }
        
        public bool UserDropShop_UserID(System.Guid UserID) {
            return base.Channel.UserDropShop_UserID(UserID);
        }
        
        public bool UserDropShop_ShopID(int ShopID) {
            return base.Channel.UserDropShop_ShopID(ShopID);
        }
        
        public bool UserChangeShop(System.Guid UserID, int ShopID) {
            return base.Channel.UserChangeShop(UserID, ShopID);
        }
        
        public int SelectShopID_UserID(System.Guid UserID) {
            return base.Channel.SelectShopID_UserID(UserID);
        }
        
        public bool UserUpdate_NoOldPassword(string UserName, string NewPassword) {
            return base.Channel.UserUpdate_NoOldPassword(UserName, NewPassword);
        }
        
        public bool UserAQUpdate_NoOldPassword(string UserName, string Question, string Answer) {
            return base.Channel.UserAQUpdate_NoOldPassword(UserName, Question, Answer);
        }
        
        public MVCpart.UserManagerService.aspnet_UsersEX[] SelectUserEXInfo_All() {
            return base.Channel.SelectUserEXInfo_All();
        }
        
        public MVCpart.UserManagerService.User_ViewModel[] SelectUserInfo_All() {
            return base.Channel.SelectUserInfo_All();
        }
        
        public bool DropUser(string UserName) {
            return base.Channel.DropUser(UserName);
        }
        
        public bool UserEXUpdate(MVCpart.UserManagerService.aspnet_UsersEX TempUserEX) {
            return base.Channel.UserEXUpdate(TempUserEX);
        }
    }
}
