//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCpart.UserSummeryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_ViewModel", Namespace="http://schemas.datacontract.org/2004/07/WCFpart.SOA.EndPoint")]
    [System.SerializableAttribute()]
    public partial class User_ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_UsersEX", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class aspnet_UsersEX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_RealNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Validation {
            get {
                return this.User_ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.User_ValidationField, value) != true)) {
                    this.User_ValidationField = value;
                    this.RaisePropertyChanged("User_Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string User_RealName {
            get {
                return this.User_RealNameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_RealNameField, value) != true)) {
                    this.User_RealNameField = value;
                    this.RaisePropertyChanged("User_RealName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string User_Phone {
            get {
                return this.User_PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PhoneField, value) != true)) {
                    this.User_PhoneField = value;
                    this.RaisePropertyChanged("User_Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string User_Adress {
            get {
                return this.User_AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.User_AdressField, value) != true)) {
                    this.User_AdressField = value;
                    this.RaisePropertyChanged("User_Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string User_Info {
            get {
                return this.User_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.User_InfoField, value) != true)) {
                    this.User_InfoField = value;
                    this.RaisePropertyChanged("User_Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserSummeryService.IUserSummery")]
    public interface IUserSummery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/UserReg", ReplyAction="http://tempuri.org/IUserSummery/UserRegResponse")]
        bool UserReg(MVCpart.UserSummeryService.User_ViewModel User, MVCpart.UserSummeryService.aspnet_UsersEX UserEX);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/UserLogOn", ReplyAction="http://tempuri.org/IUserSummery/UserLogOnResponse")]
        string UserLogOn(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/SelectUserID", ReplyAction="http://tempuri.org/IUserSummery/SelectUserIDResponse")]
        System.Guid SelectUserID(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/SelectUserInfo", ReplyAction="http://tempuri.org/IUserSummery/SelectUserInfoResponse")]
        MVCpart.UserSummeryService.User_ViewModel SelectUserInfo(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/SelectUserEXInfo", ReplyAction="http://tempuri.org/IUserSummery/SelectUserEXInfoResponse")]
        MVCpart.UserSummeryService.aspnet_UsersEX SelectUserEXInfo(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/UserUpdate", ReplyAction="http://tempuri.org/IUserSummery/UserUpdateResponse")]
        bool UserUpdate(string UserName, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/UserAQUpdate", ReplyAction="http://tempuri.org/IUserSummery/UserAQUpdateResponse")]
        bool UserAQUpdate(System.Guid UserID, string Password, string Question, string Answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserSummery/UserEXUpdate", ReplyAction="http://tempuri.org/IUserSummery/UserEXUpdateResponse")]
        bool UserEXUpdate(MVCpart.UserSummeryService.aspnet_UsersEX UserEX);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserSummeryChannel : MVCpart.UserSummeryService.IUserSummery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSummeryClient : System.ServiceModel.ClientBase<MVCpart.UserSummeryService.IUserSummery>, MVCpart.UserSummeryService.IUserSummery {
        
        public UserSummeryClient() {
        }
        
        public UserSummeryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSummeryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSummeryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSummeryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UserReg(MVCpart.UserSummeryService.User_ViewModel User, MVCpart.UserSummeryService.aspnet_UsersEX UserEX) {
            return base.Channel.UserReg(User, UserEX);
        }
        
        public string UserLogOn(string UserName, string Password) {
            return base.Channel.UserLogOn(UserName, Password);
        }
        
        public System.Guid SelectUserID(string UserName) {
            return base.Channel.SelectUserID(UserName);
        }
        
        public MVCpart.UserSummeryService.User_ViewModel SelectUserInfo(System.Guid UserID) {
            return base.Channel.SelectUserInfo(UserID);
        }
        
        public MVCpart.UserSummeryService.aspnet_UsersEX SelectUserEXInfo(System.Guid UserID) {
            return base.Channel.SelectUserEXInfo(UserID);
        }
        
        public bool UserUpdate(string UserName, string OldPassword, string NewPassword) {
            return base.Channel.UserUpdate(UserName, OldPassword, NewPassword);
        }
        
        public bool UserAQUpdate(System.Guid UserID, string Password, string Question, string Answer) {
            return base.Channel.UserAQUpdate(UserID, Password, Question, Answer);
        }
        
        public bool UserEXUpdate(MVCpart.UserSummeryService.aspnet_UsersEX UserEX) {
            return base.Channel.UserEXUpdate(UserEX);
        }
    }
}
