//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFpart.SalaryLogService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_SalaryLog", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class User_SalaryLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryLog_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SalaryLog_MarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SalaryLog_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SalaryLog_UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaryLog_ID {
            get {
                return this.SalaryLog_IDField;
            }
            set {
                if ((this.SalaryLog_IDField.Equals(value) != true)) {
                    this.SalaryLog_IDField = value;
                    this.RaisePropertyChanged("SalaryLog_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SalaryLog_Mark {
            get {
                return this.SalaryLog_MarkField;
            }
            set {
                if ((this.SalaryLog_MarkField.Equals(value) != true)) {
                    this.SalaryLog_MarkField = value;
                    this.RaisePropertyChanged("SalaryLog_Mark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SalaryLog_Time {
            get {
                return this.SalaryLog_TimeField;
            }
            set {
                if ((this.SalaryLog_TimeField.Equals(value) != true)) {
                    this.SalaryLog_TimeField = value;
                    this.RaisePropertyChanged("SalaryLog_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SalaryLog_User {
            get {
                return this.SalaryLog_UserField;
            }
            set {
                if ((this.SalaryLog_UserField.Equals(value) != true)) {
                    this.SalaryLog_UserField = value;
                    this.RaisePropertyChanged("SalaryLog_User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryLogService.ISalaryLog")]
    public interface ISalaryLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/AddSalaryLog", ReplyAction="http://tempuri.org/ISalaryLog/AddSalaryLogResponse")]
        bool AddSalaryLog(WFpart.SalaryLogService.User_SalaryLog SalaryLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/DeleteSalaryLog", ReplyAction="http://tempuri.org/ISalaryLog/DeleteSalaryLogResponse")]
        bool DeleteSalaryLog(int SalaryLogID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/UpdateSalaryLog", ReplyAction="http://tempuri.org/ISalaryLog/UpdateSalaryLogResponse")]
        bool UpdateSalaryLog(WFpart.SalaryLogService.User_SalaryLog TempSalaryLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/SelectSalaryLog_ID", ReplyAction="http://tempuri.org/ISalaryLog/SelectSalaryLog_IDResponse")]
        WFpart.SalaryLogService.User_SalaryLog SelectSalaryLog_ID(int SalaryLogID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/SelectAllSalaryLogs", ReplyAction="http://tempuri.org/ISalaryLog/SelectAllSalaryLogsResponse")]
        WFpart.SalaryLogService.User_SalaryLog[] SelectAllSalaryLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/SelectSalaryLogDIY_Func", ReplyAction="http://tempuri.org/ISalaryLog/SelectSalaryLogDIY_FuncResponse")]
        WFpart.SalaryLogService.User_SalaryLog[] SelectSalaryLogDIY_Func(System.Func<WFpart.SalaryLogService.User_SalaryLog, bool> where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryLog/SelectSalaryLogDIY_Field", ReplyAction="http://tempuri.org/ISalaryLog/SelectSalaryLogDIY_FieldResponse")]
        WFpart.SalaryLogService.User_SalaryLog[] SelectSalaryLogDIY_Field(System.Func<WFpart.SalaryLogService.User_SalaryLog, bool> where, System.Func<WFpart.SalaryLogService.User_SalaryLog, WFpart.SalaryLogService.User_SalaryLog> select);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryLogChannel : WFpart.SalaryLogService.ISalaryLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryLogClient : System.ServiceModel.ClientBase<WFpart.SalaryLogService.ISalaryLog>, WFpart.SalaryLogService.ISalaryLog {
        
        public SalaryLogClient() {
        }
        
        public SalaryLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddSalaryLog(WFpart.SalaryLogService.User_SalaryLog SalaryLog) {
            return base.Channel.AddSalaryLog(SalaryLog);
        }
        
        public bool DeleteSalaryLog(int SalaryLogID) {
            return base.Channel.DeleteSalaryLog(SalaryLogID);
        }
        
        public bool UpdateSalaryLog(WFpart.SalaryLogService.User_SalaryLog TempSalaryLog) {
            return base.Channel.UpdateSalaryLog(TempSalaryLog);
        }
        
        public WFpart.SalaryLogService.User_SalaryLog SelectSalaryLog_ID(int SalaryLogID) {
            return base.Channel.SelectSalaryLog_ID(SalaryLogID);
        }
        
        public WFpart.SalaryLogService.User_SalaryLog[] SelectAllSalaryLogs() {
            return base.Channel.SelectAllSalaryLogs();
        }
        
        public WFpart.SalaryLogService.User_SalaryLog[] SelectSalaryLogDIY_Func(System.Func<WFpart.SalaryLogService.User_SalaryLog, bool> where) {
            return base.Channel.SelectSalaryLogDIY_Func(where);
        }
        
        public WFpart.SalaryLogService.User_SalaryLog[] SelectSalaryLogDIY_Field(System.Func<WFpart.SalaryLogService.User_SalaryLog, bool> where, System.Func<WFpart.SalaryLogService.User_SalaryLog, WFpart.SalaryLogService.User_SalaryLog> select) {
            return base.Channel.SelectSalaryLogDIY_Field(where, select);
        }
    }
}
