//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFpart.GetCarService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car_Get", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class Car_Get : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GetCar_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GetCar_OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCar_UserValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCar_CarNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GetCar_ID {
            get {
                return this.GetCar_IDField;
            }
            set {
                if ((this.GetCar_IDField.Equals(value) != true)) {
                    this.GetCar_IDField = value;
                    this.RaisePropertyChanged("GetCar_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GetCar_Order {
            get {
                return this.GetCar_OrderField;
            }
            set {
                if ((this.GetCar_OrderField.Equals(value) != true)) {
                    this.GetCar_OrderField = value;
                    this.RaisePropertyChanged("GetCar_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetCar_UserValidation {
            get {
                return this.GetCar_UserValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCar_UserValidationField, value) != true)) {
                    this.GetCar_UserValidationField = value;
                    this.RaisePropertyChanged("GetCar_UserValidation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string GetCar_CarNumber {
            get {
                return this.GetCar_CarNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCar_CarNumberField, value) != true)) {
                    this.GetCar_CarNumberField = value;
                    this.RaisePropertyChanged("GetCar_CarNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetCarService.IGetCar")]
    public interface IGetCar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/AddCarGet", ReplyAction="http://tempuri.org/IGetCar/AddCarGetResponse")]
        bool AddCarGet(WFpart.GetCarService.Car_Get CarGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/DeleteCarGet", ReplyAction="http://tempuri.org/IGetCar/DeleteCarGetResponse")]
        bool DeleteCarGet(int CarGetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/UpdateCarGet", ReplyAction="http://tempuri.org/IGetCar/UpdateCarGetResponse")]
        bool UpdateCarGet(WFpart.GetCarService.Car_Get TempCarGet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/SelectCarGet_ID", ReplyAction="http://tempuri.org/IGetCar/SelectCarGet_IDResponse")]
        WFpart.GetCarService.Car_Get SelectCarGet_ID(int CarGetID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/SelectAllCarGets", ReplyAction="http://tempuri.org/IGetCar/SelectAllCarGetsResponse")]
        WFpart.GetCarService.Car_Get[] SelectAllCarGets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/SelectCarGetDIY_Func", ReplyAction="http://tempuri.org/IGetCar/SelectCarGetDIY_FuncResponse")]
        WFpart.GetCarService.Car_Get[] SelectCarGetDIY_Func(System.Func<WFpart.GetCarService.Car_Get, bool> where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCar/SelectCarGetDIY_Field", ReplyAction="http://tempuri.org/IGetCar/SelectCarGetDIY_FieldResponse")]
        WFpart.GetCarService.Car_Get[] SelectCarGetDIY_Field(System.Func<WFpart.GetCarService.Car_Get, bool> where, System.Func<WFpart.GetCarService.Car_Get, WFpart.GetCarService.Car_Get> select);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetCarChannel : WFpart.GetCarService.IGetCar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCarClient : System.ServiceModel.ClientBase<WFpart.GetCarService.IGetCar>, WFpart.GetCarService.IGetCar {
        
        public GetCarClient() {
        }
        
        public GetCarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCarGet(WFpart.GetCarService.Car_Get CarGet) {
            return base.Channel.AddCarGet(CarGet);
        }
        
        public bool DeleteCarGet(int CarGetID) {
            return base.Channel.DeleteCarGet(CarGetID);
        }
        
        public bool UpdateCarGet(WFpart.GetCarService.Car_Get TempCarGet) {
            return base.Channel.UpdateCarGet(TempCarGet);
        }
        
        public WFpart.GetCarService.Car_Get SelectCarGet_ID(int CarGetID) {
            return base.Channel.SelectCarGet_ID(CarGetID);
        }
        
        public WFpart.GetCarService.Car_Get[] SelectAllCarGets() {
            return base.Channel.SelectAllCarGets();
        }
        
        public WFpart.GetCarService.Car_Get[] SelectCarGetDIY_Func(System.Func<WFpart.GetCarService.Car_Get, bool> where) {
            return base.Channel.SelectCarGetDIY_Func(where);
        }
        
        public WFpart.GetCarService.Car_Get[] SelectCarGetDIY_Field(System.Func<WFpart.GetCarService.Car_Get, bool> where, System.Func<WFpart.GetCarService.Car_Get, WFpart.GetCarService.Car_Get> select) {
            return base.Channel.SelectCarGetDIY_Field(where, select);
        }
    }
}
