//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFpart.SalaryAppendService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_SalaryAppend", Namespace="http://schemas.datacontract.org/2004/07/WCFpart")]
    [System.SerializableAttribute()]
    public partial class User_SalaryAppend : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryAppend_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SalaryAppend_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryAppend_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SalaryAppend_TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalaryAppend_InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaryAppend_ID {
            get {
                return this.SalaryAppend_IDField;
            }
            set {
                if ((this.SalaryAppend_IDField.Equals(value) != true)) {
                    this.SalaryAppend_IDField = value;
                    this.RaisePropertyChanged("SalaryAppend_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SalaryAppend_User {
            get {
                return this.SalaryAppend_UserField;
            }
            set {
                if ((this.SalaryAppend_UserField.Equals(value) != true)) {
                    this.SalaryAppend_UserField = value;
                    this.RaisePropertyChanged("SalaryAppend_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal SalaryAppend_Price {
            get {
                return this.SalaryAppend_PriceField;
            }
            set {
                if ((this.SalaryAppend_PriceField.Equals(value) != true)) {
                    this.SalaryAppend_PriceField = value;
                    this.RaisePropertyChanged("SalaryAppend_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime SalaryAppend_Time {
            get {
                return this.SalaryAppend_TimeField;
            }
            set {
                if ((this.SalaryAppend_TimeField.Equals(value) != true)) {
                    this.SalaryAppend_TimeField = value;
                    this.RaisePropertyChanged("SalaryAppend_Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SalaryAppend_Info {
            get {
                return this.SalaryAppend_InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryAppend_InfoField, value) != true)) {
                    this.SalaryAppend_InfoField = value;
                    this.RaisePropertyChanged("SalaryAppend_Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryAppendService.ISalaryAppend")]
    public interface ISalaryAppend {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/AddSalaryAppend", ReplyAction="http://tempuri.org/ISalaryAppend/AddSalaryAppendResponse")]
        bool AddSalaryAppend(WFpart.SalaryAppendService.User_SalaryAppend SalaryAppend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/DeleteSalaryAppend", ReplyAction="http://tempuri.org/ISalaryAppend/DeleteSalaryAppendResponse")]
        bool DeleteSalaryAppend(int SalaryAppendID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/UpdateSalaryAppend", ReplyAction="http://tempuri.org/ISalaryAppend/UpdateSalaryAppendResponse")]
        bool UpdateSalaryAppend(WFpart.SalaryAppendService.User_SalaryAppend TempSalaryAppend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/SelectSalaryAppend_ID", ReplyAction="http://tempuri.org/ISalaryAppend/SelectSalaryAppend_IDResponse")]
        WFpart.SalaryAppendService.User_SalaryAppend SelectSalaryAppend_ID(int SalaryAppendID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/SelectAllSalaryAppends", ReplyAction="http://tempuri.org/ISalaryAppend/SelectAllSalaryAppendsResponse")]
        WFpart.SalaryAppendService.User_SalaryAppend[] SelectAllSalaryAppends();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/SelectSalaryAppendDIY_Func", ReplyAction="http://tempuri.org/ISalaryAppend/SelectSalaryAppendDIY_FuncResponse")]
        WFpart.SalaryAppendService.User_SalaryAppend[] SelectSalaryAppendDIY_Func(System.Func<WFpart.SalaryAppendService.User_SalaryAppend, bool> where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryAppend/SelectSalaryAppendDIY_Field", ReplyAction="http://tempuri.org/ISalaryAppend/SelectSalaryAppendDIY_FieldResponse")]
        WFpart.SalaryAppendService.User_SalaryAppend[] SelectSalaryAppendDIY_Field(System.Func<WFpart.SalaryAppendService.User_SalaryAppend, bool> where, System.Func<WFpart.SalaryAppendService.User_SalaryAppend, WFpart.SalaryAppendService.User_SalaryAppend> select);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryAppendChannel : WFpart.SalaryAppendService.ISalaryAppend, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryAppendClient : System.ServiceModel.ClientBase<WFpart.SalaryAppendService.ISalaryAppend>, WFpart.SalaryAppendService.ISalaryAppend {
        
        public SalaryAppendClient() {
        }
        
        public SalaryAppendClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryAppendClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryAppendClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryAppendClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddSalaryAppend(WFpart.SalaryAppendService.User_SalaryAppend SalaryAppend) {
            return base.Channel.AddSalaryAppend(SalaryAppend);
        }
        
        public bool DeleteSalaryAppend(int SalaryAppendID) {
            return base.Channel.DeleteSalaryAppend(SalaryAppendID);
        }
        
        public bool UpdateSalaryAppend(WFpart.SalaryAppendService.User_SalaryAppend TempSalaryAppend) {
            return base.Channel.UpdateSalaryAppend(TempSalaryAppend);
        }
        
        public WFpart.SalaryAppendService.User_SalaryAppend SelectSalaryAppend_ID(int SalaryAppendID) {
            return base.Channel.SelectSalaryAppend_ID(SalaryAppendID);
        }
        
        public WFpart.SalaryAppendService.User_SalaryAppend[] SelectAllSalaryAppends() {
            return base.Channel.SelectAllSalaryAppends();
        }
        
        public WFpart.SalaryAppendService.User_SalaryAppend[] SelectSalaryAppendDIY_Func(System.Func<WFpart.SalaryAppendService.User_SalaryAppend, bool> where) {
            return base.Channel.SelectSalaryAppendDIY_Func(where);
        }
        
        public WFpart.SalaryAppendService.User_SalaryAppend[] SelectSalaryAppendDIY_Field(System.Func<WFpart.SalaryAppendService.User_SalaryAppend, bool> where, System.Func<WFpart.SalaryAppendService.User_SalaryAppend, WFpart.SalaryAppendService.User_SalaryAppend> select) {
            return base.Channel.SelectSalaryAppendDIY_Field(where, select);
        }
    }
}
